<?php

namespace AppBundle\Repository;

/**
 * AbonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByCode($code)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Abonne a
                 WHERE a.codeabonne = :code'
            )->setParameter('code', $code)
            ->getResult();
    }

    public function findOneByNom($nom)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Abonne a
                 WHERE a.nom = :nom'
            )->setParameter('nom', $nom)
            ->getResult();
    }

    public function findOneById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Abonne a
                 WHERE a.id = :id'
            )->setParameter('id', $id)
            ->getResult();
    }

    public function findByAbonnes()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Abonne a
                ORDER BY a.nom'
            )->getResult();
    }
}
