<?php

namespace AppBundle\Repository;

/**
 * AbonneEnvoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonneEnvoiRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByIdAbonneMois($id_abonne, $mois)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a, e FROM AppBundle:AbonneEnvoi a
                 JOIN a.envoi e
                 WHERE a.abonne = :abonne
                   AND e.date LIKE :mois
                   AND e.etat != :suppr'
            )->setParameter('abonne', $id_abonne)
            ->setParameter('mois', $mois)
            ->setParameter('suppr', 'suppr')
            ->getResult();
    }

    public function findByIdAbonneMoisEchelle($id_abonne, $mois, $echelle)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a, e FROM AppBundle:AbonneEnvoi a
                 JOIN a.envoi e
                 WHERE a.abonne = :abonne
                 AND e.echelle = :echelle
                 AND e.date LIKE :mois
                 AND e.etat != :suppr
                 ORDER BY e.agence, e.date'
            )->setParameter('abonne', $id_abonne)
            ->setParameter('echelle', $echelle)
            ->setParameter('mois', $mois)
            ->setParameter('suppr', 'suppr')
            ->getResult();
    }



    public function findOneByIdEnvoi($envoi)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AbonneEnvoi a
                 WHERE a.envoi = :envoi'
            )->setParameter('envoi', $envoi)
            ->getResult();
    }

}
