<?php

namespace AppBundle\Repository;

/**
 * AgenceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceUserRepository extends \Doctrine\ORM\EntityRepository
{
}
