<?php

namespace AppBundle\Repository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAG()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Agence a
                 WHERE a.statut = :statut
                 ORDER BY a.nom'
            )->setParameter('statut', 'AG')
            ->getResult();
    }

    public function findByAgences()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Agence a
                 ORDER BY a.nom'
            )->getResult();
    }

    public function findByPD()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Agence a
                 WHERE a.statut = :statut
                 ORDER BY a.nom'
            )->setParameter('statut', 'PD')
            ->getResult();
    }

    public function findByPR()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Agence a
                 WHERE a.statut = :statut
                 ORDER BY a.nom'
            )->setParameter('statut', 'PR')
            ->getResult();
    }

    public function findByStatut()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT a.statut FROM AppBundle:Agence a
                 ORDER BY a.statut')
            ->getResult();
    }

    public function findByStatutAgenceNom($statut)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT a FROM AppBundle:Agence a
                 WHERE a.statut = :statut
                 ORDER BY a.nom'
            )->setParameter('statut', $statut)
            ->getResult();
    }

    public function findOneById($agence)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Agence a
                 WHERE a.id = :id'
            )->setParameter('id', $agence)
            ->getResult();
    }

    public function findOneByDG()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Agence a
                 WHERE a.statut = :statut'
            )->setParameter('statut', 'DG')
            ->getResult();
    }
}
