<?php

namespace AppBundle\Repository;

/**
 * CoursierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursierRepository extends \Doctrine\ORM\EntityRepository
{
}
