<?php

namespace AppBundle\Repository;

/**
 * DepecheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepecheRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByIdAgenceAnnee($agence, $annee)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT d FROM AppBundle:Depeche d
                 WHERE  d.agence=:agence
                 AND    d.journee LIKE :annee
                 AND    d.etat = :etat'
                    )->setParameter('agence', $agence)
                     ->setParameter('annee', $annee)
                     ->setParameter('etat', 'En fermeture')
            ->getResult();
    }
    
    public function findByIdAgenceAnneeTransmis($agence, $annee)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT d FROM AppBundle:Depeche d
                 WHERE  d.agence=:agence
                 AND    d.journee LIKE :annee
                 AND    d.etat = :etat'
                    )->setParameter('agence', $agence)
                     ->setParameter('annee', $annee)
                     ->setParameter('etat', 'Transmis')
            ->getResult();
    }
    
    public function findOneById($depeche)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT d FROM AppBundle:Depeche d
                     WHERE d.id = :id'
            )->setParameter('id', $depeche)
            ->getResult();
    }
    
}
