<?php

namespace AppBundle\Repository;

/**
 * DestinataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinataireRepository extends \Doctrine\ORM\EntityRepository
{
}
