<?php

namespace AppBundle\Repository;

/**
 * ExpediteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpediteurRepository extends \Doctrine\ORM\EntityRepository
{
}
