<?php

namespace AppBundle\Repository;

/**
 * VacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByIdUser($utilisateur)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM AppBundle:Vacation v
                 WHERE v.utilisateur = :utilisateur
                 '
            )->setParameter('utilisateur', $utilisateur)
            ->getResult();
    }


    public function findByIdUserMois($id_user, $journneemois)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM AppBundle:Vacation v
                      WHERE v.journee LIKE :journneemois
                      AND v.utilisateur= :utilisateur
                      ORDER BY v.journee'
            )->setParameter('journneemois', $journneemois)
            ->setParameter('utilisateur', $id_user)
            ->getResult();
    }

    public function findByIdUserDate($utilisateur, $date)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM AppBundle:Vacation v
                 WHERE v.utilisateur = :utilisateur
                 AND   v.journee = :journee'
                    )->setParameter('utilisateur', $utilisateur)
                    ->setParameter('journee', $date)
            ->getResult();
    }

    public function findByIdDate($date)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM AppBundle:Vacation v
                 WHERE v.journee = :journee
                ORDER BY v.id DESC'
            )->setParameter('journee', $date)
            ->getResult();
    }

    public function findOneById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM AppBundle:Vacation v
                 WHERE v.id = :id'
            )->setParameter('id', $id)
            ->getResult();
    }

    public function findByUserAnnee($utilisateur, $annee)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM AppBundle:Vacation v
                 WHERE v.utilisateur = :utilisateur
                 AND v.annee = :annee'
            )->setParameter('utilisateur', $utilisateur)
             ->setParameter('annee', $annee)
             ->getResult();
    }

    public function findByMoisAgence($mois, $agence)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM AppBundle:Vacation v
                 WHERE v.journee LIKE :mois
                 AND v.agence = :agence'
            )->setParameter('mois', $mois)
            ->setParameter('agence', $agence)
            ->getResult();
    }

    public function findByAgence($agence)
    {
        return $this->getEntityManager()
             ->createQuery(
                'SELECT v FROM AppBundle:Vacation v
                 WHERE v.agence = :agence'
            )->setParameter('agence', $agence)
             ->getResult();
    }




}
